# Generated by Django 5.1.5 on 2025-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='operation',
            field=models.CharField(choices=[('INCREASE', 'Increase (Stock In)'), ('DECREASE', 'Decrease (Stock Out)')], default='INCREASE', max_length=10),
        ),
    ]
